import { useEffect, useRef, useState } from 'react';
import { Link } from 'react-router-dom';
import { api, type Project } from '../api';
import { reviewDemoProject, type DemoProject } from '../demoProjects';
import { getDemoUser } from '../demoSession';
import ProjectCard from '../components/ProjectCard';
export default function AdminPage() {
 const [projects,setProjects]=useState<Project[]>([]); const [filter,setFilter]=useState('all'); const [query,setQuery]=useState(''); const [selected,setSelected]=useState<DemoProject|null>(null); const [decision,setDecision]=useState<'approve'|'corrections'|null>(null); const [text,setText]=useState(''); const [error,setError]=useState(''); const [notice,setNotice]=useState(''); const dialog=useRef<HTMLDialogElement>(null);
 const load=()=>api.adminListProjects().then(setProjects).catch(()=>setError('No se pudieron cargar los proyectos.'));
 useEffect(()=>{load();},[]);
 useEffect(()=>{if(selected)dialog.current?.showModal();else dialog.current?.close();},[selected]);
 const pending=projects.filter(p=>p.status==='pending'); const visible=projects.filter(p=>(filter==='all'||p.status===filter)&&(p.name+' '+p.repo_url).toLowerCase().includes(query.toLowerCase()));
 function close(){setSelected(null);setDecision(null);setText('');setError('');}
 return <div className="space-y-6"><header><h1 className="text-3xl font-semibold">Proyectos</h1><p className="mt-2 text-sm text-atlas-muted">Solicitudes pendientes y proyectos registrados en la plataforma.</p></header>{notice&&<p role="status" className="rounded-lg bg-atlas-mist p-3 text-sm">{notice}</p>}{error&&!selected&&<p role="alert">{error}</p>}
 <section><h2 className="mb-4 text-xl font-semibold">Pendientes de revisión <span className="text-atlas-muted">({pending.length})</span></h2><div className="grid gap-4 lg:grid-cols-2 xl:grid-cols-3">{pending.map(p=><button key={p.id} className="rounded-xl border border-atlas-mist p-5 text-left hover:border-atlas-red" onClick={()=>{setSelected(p as DemoProject);setText('');setDecision(null);setError('');}}><h3 className="font-semibold">{p.name}</h3><p className="mt-2 text-sm text-atlas-muted">{(p as DemoProject).owner}</p><p className="mt-1 break-all text-xs text-atlas-muted">{p.repo_url}</p><span className="mt-4 block text-sm font-medium text-atlas-red">Ver solicitud →</span></button>)}</div>{!pending.length&&<p className="text-sm text-atlas-muted">No hay solicitudes pendientes.</p>}</section>
 <section><h2 className="mb-4 text-xl font-semibold">Todos los proyectos</h2><label className="block text-sm">Buscar proyecto<input className="ml-3 rounded-lg border border-atlas-mist p-2" value={query} onChange={e=>setQuery(e.target.value)} placeholder="Nombre o repositorio"/></label><div className="my-4 flex flex-wrap gap-2">{[['all','Todos'],['running','Desplegados'],['building','CI en ejecución'],['ci_pending','CI pendiente'],['pending','Validación pendiente'],['corrections','Por corregir'],['failed','Despliegue fallido'],['ci_failed','CI fallido'],['retained','Retenidos']].map(([value,label])=><button key={value} aria-pressed={filter===value} onClick={()=>setFilter(value)} className={`rounded-full px-3 py-2 text-xs ${filter===value?'bg-atlas-red text-white':'bg-atlas-mist'}`}>{label}</button>)}</div><div className="grid gap-4 lg:grid-cols-2 xl:grid-cols-3">{visible.map(p=><ProjectCard key={p.id} project={p}/>)}</div><p className="mt-4 text-xs text-atlas-muted">Mostrando {visible.length} de {projects.length} proyectos</p></section>
 <dialog ref={dialog} onCancel={close} className="m-auto max-h-[90dvh] w-[calc(100%-2rem)] max-w-xl overflow-y-auto rounded-2xl p-6 backdrop:bg-black/50" aria-labelledby="review-title">{selected&&<><h2 id="review-title" className="text-xl font-semibold">{decision==='approve'?'Confirmar validación':decision==='corrections'?'Solicitar correcciones':'Detalle de la solicitud'}</h2><h3 className="mt-4 font-semibold">{selected.name}</h3><dl className="my-4 divide-y divide-atlas-mist text-sm">{Object.entries({Responsable:selected.owner,Repositorio:selected.submission?.repo||selected.repo_url,Rama:selected.branch,'Commit presentado':selected.submission?.commit||'No disponible',Tipo:selected.submission?.type||'No disponible',Asignatura:selected.submission?.academic?selected.submission.course:'No aplica','Propósito funcional':selected.submission?.purpose||'No disponible'}).map(([label,value])=><div key={label} className="py-3"><dt className="text-xs text-atlas-muted">{label}</dt><dd className="mt-1 break-all">{value}</dd></div>)}</dl>{!decision?<div className="flex flex-wrap justify-end gap-3"><button onClick={close}>Cerrar</button><Link to={`/projects/${selected.id}`} className="text-atlas-red">Ver proyecto</Link><button disabled={!getDemoUser()} onClick={()=>setDecision('corrections')} className="rounded-lg border p-2">Solicitar correcciones</button><button disabled={!getDemoUser()} onClick={()=>setDecision('approve')} className="rounded-lg bg-atlas-red p-2 text-white">Validar</button></div>:<form onSubmit={e=>{e.preventDefault();try{reviewDemoProject(selected.id,decision,text);setNotice(decision==='approve'?'Proyecto validado. CI pendiente.':'Correcciones solicitadas al desarrollador.');close();load();}catch(cause){setError((cause as Error).message);}}}><label className="block text-sm">{decision==='approve'?`Escribe exactamente ${selected.submission.repo}`:'Explicación obligatoria'}<textarea required value={text} onChange={e=>setText(e.target.value)} className="mt-2 w-full rounded border border-atlas-mist p-3" rows={decision==='approve'?1:4}/></label>{error&&<p role="alert" className="my-3 text-sm text-atlas-red">{error}</p>}<div className="mt-4 flex justify-end gap-3"><button type="button" onClick={()=>{setDecision(null);setText('');setError('');}}>Atrás</button><button className="rounded-lg bg-atlas-red p-3 text-sm text-white">{decision==='approve'?'Validar proyecto':'Enviar solicitud'}</button></div></form>}</>}</dialog>
 </div>;
}
