import { useState } from 'react';
import { clusterDemo as c } from '../demoFixtures';
import { listDemoProjects } from '../demoProjects';
import { getDemoUser } from '../demoSession';
const box='rounded-xl border border-atlas-mist bg-white p-5';
export default function ClusterPage() {
 const [audit,setAudit]=useState(true);
 if(!getDemoUser())return <p>La información detallada del clúster requiere conectar el servicio de infraestructura.</p>;
 const projects=listDemoProjects(true);
 const history=projects.flatMap(p=>(p.history||[]).map(h=>({...h,project:p.name}))).sort((a,b)=>b.date.localeCompare(a.date)).slice(0,8);
 return <div className="space-y-6">
 <header className="flex flex-wrap items-center justify-between gap-3"><div><h1 className="text-3xl font-semibold">Estado del clúster</h1><p className="mt-2 text-sm text-atlas-muted">Infraestructura de demostración · Instantánea del prototipo, sin métricas en vivo.</p></div><span className="rounded-full bg-green-100 px-3 py-1 text-xs text-green-800">Clúster saludable · demo</span></header>
 <div className="grid grid-cols-2 gap-4 lg:grid-cols-4">{[['Nodos',c.nodes],['Pods',c.pods],['CPU',`${c.cpu_usage}%`],['Memoria',`${c.memory_usage}%`]].map(([label,value])=><div key={label} className={box}><p className="text-sm text-atlas-muted">{label}</p><p className="mt-2 text-3xl font-semibold">{value}</p>{String(value).includes('%')&&<progress aria-label={String(label)} value={parseInt(String(value))} max={100} className="mt-3 h-2 w-full accent-atlas-red"/>}</div>)}</div>
 <div className="grid gap-5 xl:grid-cols-2"><section className={`${box} overflow-x-auto`}><h2 className="mb-4 font-semibold">Nodos</h2><table className="w-full text-left text-sm"><thead className="text-xs text-atlas-muted"><tr><th className="pb-3">Nombre</th><th>Estado</th><th>CPU</th><th>Memoria</th></tr></thead><tbody>{c.machines.map(([name,cpu,memory])=><tr key={name} className="border-t border-atlas-mist"><td className="py-3">{name}</td><td className="text-green-800">Listo</td><td>{cpu}%</td><td>{memory}%</td></tr>)}</tbody></table></section>
 <section className={box}><h2 className="font-semibold">Uso de recursos · últimos 60 min</h2><p className="mt-1 text-xs text-atlas-muted">Muestra simulada · porcentaje de utilización</p><svg viewBox="0 0 420 180" role="img" aria-label="CPU y memoria de demostración; última muestra 43 y 62 por ciento" className="mt-5 w-full">{[0,50,100].map(n=><g key={n}><text x="0" y={155-n*1.3} fontSize="10" fill="#62625E">{n}%</text><path d={`M35 ${150-n*1.3}H410`} stroke="#EBEBEB"/></g>)}{[c.cpu,c.memory].map((values,i)=><polyline key={i} fill="none" stroke={i?'#1D1D1B':'#A00000'} strokeDasharray={i?'5 4':undefined} strokeWidth="2.5" points={values.map((value,index)=>`${35+index*37.5},${150-value*1.3}`).join(' ')}/>)}<text x="35" y="176" fontSize="10">−60 min</text><text x="377" y="176" fontSize="10">Ahora</text></svg><p className="flex gap-5 text-xs"><span className="text-atlas-red">━ CPU</span><span>┄ Memoria</span></p></section></div>
 <div className="grid gap-5 xl:grid-cols-2"><section className={box}><h2 className="mb-5 font-semibold">Almacenamiento</h2><div className="flex justify-between text-sm"><span>Usado: 512 GB</span><span>Total: 1.2 TB</span></div><progress aria-label="Almacenamiento utilizado" max={100} value={43} className="my-4 h-3 w-full accent-atlas-red"/><p className="text-xs text-atlas-muted">43% utilizado</p></section><section className={box}><h2 className="mb-4 font-semibold">Pods por estado</h2>{[['En ejecución',98],['Pendiente',12],['Fallido',6],['Desconocido',12]].map(([label,value])=><div className="mb-2 grid grid-cols-[1fr_60px] text-sm" key={label}><span>{label}</span><strong>{value} <small className="font-normal text-atlas-muted">· {Math.round(Number(value)/128*100)}%</small></strong></div>)}</section></div>
 <div className="grid gap-5 xl:grid-cols-2">{[
 ['Certificados TLS',[['recomendador-libros','Vigente · 48 días'],['portal-tutorias','Vence en 12 días'],['api-biblioteca','Vence en 8 días']]],
 ['Trabajos de la plataforma',[['CI/CD activos','7'],['En cola','3'],['Requiere atención','1 · hace 18 min']]],
 ].map(([title,rows])=><section key={String(title)} className={box}><h2 className="mb-4 font-semibold">{String(title)}</h2>{(rows as string[][]).map(([label,value])=><div key={label} className="flex flex-wrap justify-between gap-2 border-t border-atlas-mist py-3 text-sm"><span>{label}</span><strong>{value}</strong></div>)}</section>)}</div>
 <div className="grid grid-cols-2 gap-4 lg:grid-cols-4">{[['Aplicaciones desplegadas',30],['Despliegues activos',4],['Proyectos suspendidos',2],['Proyectos fallidos',3]].map(([label,value])=><div className={box} key={label}><p className="text-2xl font-semibold">{value}</p><p className="mt-2 text-xs text-atlas-muted">{label}</p></div>)}</div><p className="text-xs text-atlas-muted">Los totales del clúster representan toda la plataforma simulada; el catálogo muestra una selección de proyectos.</p>
 <section className={box}><div className="flex justify-between gap-4"><h2 className="font-semibold">Historial de auditoría</h2><button className="text-sm text-atlas-red" aria-expanded={audit} onClick={()=>setAudit(!audit)}>{audit?'Ocultar':'Mostrar'} historial</button></div>{audit&&<ul className="mt-4 divide-y divide-atlas-mist">{history.map((h,index)=><li key={index} className="py-3 text-sm"><strong>{h.action}</strong><p className="mt-1 text-xs text-atlas-muted">{h.project} · {h.actor} · {new Date(h.date).toLocaleString('es-CO')}</p></li>)}</ul>}</section>
 </div>;
}
