import { useRef, useState } from 'react';
import { Link, useParams } from 'react-router-dom';
import { commits, listDemoProjects, updateDemoProject, type DemoProject } from '../demoProjects';
import { getDemoUser } from '../demoSession';
import StatusBadge from '../components/StatusBadge';
import CustomSelect from '../components/CustomSelect';
import { useToast } from '../components/ToastProvider';
export default function DemoProjectDetailPage(){
 const showToast=useToast();
 const {id}=useParams(); const [revision,refresh]=useState(0); const [tab,setTab]=useState('Resumen'); const [purpose,setPurpose]=useState(''); const [reason,setReason]=useState(''); const [confirmation,setConfirmation]=useState(''); const [days,setDays]=useState(14); const [retention,setRetention]=useState(15); const dialog=useRef<HTMLDialogElement>(null);
 const p=listDemoProjects(true).find(p=>p.id===id); void revision;
 if(!p)return <p>Proyecto no encontrado. <Link to="/" className="text-atlas-red">Volver</Link></p>;
 const admin=getDemoUser()?.role==='admin'; const owner=p.ownerId===getDemoUser()?.id;
 const change=(patch:Partial<DemoProject>,action:string)=>{try{updateDemoProject(p.id,patch,action);showToast(action);refresh(n=>n+1);}catch(cause){showToast((cause as Error).message);}};
 return <div className="space-y-6"><Link to={admin?'/admin/projects':'/'} className="text-sm text-atlas-red">← Proyectos</Link><header className="flex flex-wrap items-start justify-between gap-4"><div><h1 className="text-3xl font-semibold">{p.name}</h1><p className="mt-2 break-all text-sm text-atlas-muted">{p.submission.repo} · {p.branch}</p></div><StatusBadge status={p.status}/></header>
 {p.observation&&<section className="rounded-xl border border-amber-300 bg-amber-50 p-5"><h2 className="font-semibold">Observaciones de la revisión</h2><p className="mt-2 text-sm">{p.observation}</p>{owner&&p.status==='corrections'&&<form className="mt-4 space-y-3" onSubmit={e=>{e.preventDefault();if(!purpose.trim())return;change({status:'pending',submission:{...p.submission,purpose:purpose.trim(),commit:commits[0].sha}},'Correcciones presentadas. Validación pendiente.');}}><label className="atlas-field"><span className="atlas-field-label">Propósito actualizado</span><textarea required value={purpose} onChange={e=>setPurpose(e.target.value)} className="atlas-control"/></label><p className="text-xs text-atlas-muted">Se utilizará automáticamente el último commit de la rama configurada.</p><button className="rounded-lg bg-atlas-red px-4 py-2 text-sm text-white">Enviar a validación</button></form>}</section>}
 {p.deletion&&<section className="rounded-xl border border-atlas-red p-4 text-sm"><h2 className="font-semibold">Solicitud administrativa de eliminación</h2><p className="mt-2">{p.deletion.reason}</p><p className="mt-2">Plazo: {p.deletion.days} días · Vencimiento: {new Date(p.deletion.deadline).toLocaleDateString('es-CO')} · Retención: {p.deletion.retention} días</p><p className="mt-2">La aplicación continúa funcionando durante el plazo.</p></section>}
 {p.status==='retained'&&<section className="rounded-xl bg-atlas-mist p-5"><h2 className="font-semibold">Datos retenidos</h2><p className="mt-2 text-sm">La aplicación está detenida. Retención hasta {p.retentionUntil}.</p><button className="mt-4 text-sm text-atlas-red" onClick={()=>showToast('La exportación de datos requiere conectar el almacenamiento real.')}>Exportar datos</button>{owner&&<button className="ml-4 text-sm text-atlas-red" onClick={()=>change({status:'recovery_pending'},'Recuperación solicitada. Pendiente de restauración técnica.')}>Solicitar recuperación</button>}</section>}
 <nav aria-label="Secciones del proyecto" className="flex flex-wrap gap-2 border-b border-atlas-mist pb-3">{['Resumen','Builds','Logs','Configuración','Historial'].map(item=><button key={item} aria-pressed={tab===item} onClick={()=>setTab(item)} className={`rounded-lg px-4 py-2 text-sm ${tab===item?'bg-atlas-red text-white':'bg-atlas-mist'}`}>{item}</button>)}</nav>
 {tab==='Resumen'&&<><div className="grid gap-4 sm:grid-cols-3">{[['Admisión',['pending','corrections'].includes(p.status)?p.status:'approved'],['CI',p.status==='ci_failed'?'failed':p.status==='ci_pending'?'ci_pending':p.status==='building'?'building':p.status==='ci_failed'?'failed':p.builds?.length?'passed':'not_started'],['Despliegue',p.domain?'running':p.status==='failed'?'failed':'not_deployed']].map(([label,value])=><div key={label} className="rounded-xl border border-atlas-mist p-4"><h2 className="mb-3 text-sm text-atlas-muted">{label}</h2><StatusBadge status={value}/></div>)}</div><section className="rounded-xl border border-atlas-mist p-5"><h2 className="font-semibold">Información del proyecto</h2><p className="mt-3 text-sm">{p.submission.purpose}</p><dl className="mt-4 space-y-3 text-sm">{Object.entries({'Proyecto creado':new Date(p.created_at).toLocaleDateString('es-CO'),Responsable:p.owner,Asignatura:p.submission.academic?p.submission.course:'No aplica','Commit presentado':p.submission.commit,'URL de ejemplo':p.domain||'No disponible'}).map(([label,value])=><div key={label}><dt className="text-xs text-atlas-muted">{label}</dt><dd className="mt-1 break-all">{value}</dd></div>)}</dl></section></>}
 {['Builds','Logs'].includes(tab)&&<section className="space-y-3">{!p.builds?.length&&<p className="text-sm text-atlas-muted">Todavía no hay ejecuciones. El proceso técnico comienza después de la admisión.</p>}{p.builds?.map(b=><article key={b.id} className="rounded-xl border border-atlas-mist p-5"><div className="flex justify-between gap-3"><h2 className="font-semibold">{b.commit_message}</h2><StatusBadge status={b.status}/></div><p className="mt-2 break-all text-xs text-atlas-muted">{b.commit_sha}</p><pre className="mt-4 whitespace-pre-wrap rounded-lg bg-atlas-ink p-4 text-xs text-white">{b.logs}</pre></article>)}</section>}
 {tab==='Configuración'&&<section className="rounded-xl border border-atlas-mist p-5"><h2 className="font-semibold">Configuración de despliegue</h2><dl className="mt-4 space-y-3 text-sm">{Object.entries({Repositorio:p.submission.repo,Rama:p.branch,Puerto:p.submission.port,Build:p.submission.build}).map(([k,v])=><div key={k}><dt className="text-atlas-muted">{k}</dt><dd>{v}</dd></div>)}</dl><p className="mt-5 text-xs text-atlas-muted">El repositorio no puede sustituirse. Los cambios de configuración requieren la integración real.</p></section>}
 {tab==='Historial'&&<ul className="divide-y divide-atlas-mist">{p.history?.map((h,index)=><li key={index} className="py-4 text-sm"><strong>{h.action}</strong><p className="mt-1 text-xs text-atlas-muted">{h.actor} · {new Date(h.date).toLocaleString('es-CO')}</p></li>)}</ul>}
 {!['retained','recovery_pending','deleted'].includes(p.status)&&<button className="text-sm text-atlas-red" onClick={()=>{setReason('');setConfirmation('');dialog.current?.showModal();}}>{admin?'Solicitar eliminación':'Eliminar proyecto'}</button>}
 <dialog ref={dialog} aria-labelledby="deletion-title" className="m-auto max-h-[90dvh] w-[calc(100%-2rem)] max-w-lg overflow-auto rounded-xl p-6 backdrop:bg-black/50"><form onSubmit={e=>{e.preventDefault();if(confirmation!==p.submission.repo){showToast('El nombre del repositorio no coincide.');return;}if(admin){if(!reason.trim())return;change({deletion:{reason:reason.trim(),days,retention,deadline:new Date(Date.now()+days*86400000).toISOString()}},'Solicitud administrativa de eliminación registrada.');}else{change({status:'retained',domain:null,retentionUntil:new Date(Date.now()+15*86400000).toISOString().slice(0,10)},'Eliminación voluntaria: aplicación detenida, datos retenidos durante 15 días.');}dialog.current?.close();}}><h2 id="deletion-title" className="text-xl font-semibold">{admin?'Solicitar eliminación':'Confirmar eliminación'}</h2><p className="my-4 text-sm">{admin?'La aplicación continuará en servicio durante el plazo.':'Se detendrá la aplicación y se retirará el tráfico. Los datos se conservarán 15 días; el repositorio no se eliminará.'}</p>{admin&&<><label className="atlas-field"><span className="atlas-field-label">Motivo obligatorio</span><textarea required value={reason} onChange={e=>setReason(e.target.value)} className="atlas-control"/></label><CustomSelect label="Plazo" className="mt-4" value={String(days)} onChange={value=>setDays(Number(value))} options={[7,14,21].map(n=>({value:String(n),label:`${n} días`}))} /><CustomSelect label="Retención posterior" className="mt-4" value={String(retention)} onChange={value=>setRetention(Number(value))} options={[15,30].map(n=>({value:String(n),label:`${n} días`}))} /></>}<label className="atlas-field mt-4"><span className="atlas-field-label">Escribe exactamente {p.submission.repo}</span><input required value={confirmation} onChange={e=>setConfirmation(e.target.value)} aria-invalid={Boolean(confirmation && confirmation !== p.submission.repo)} className="atlas-control"/></label>{confirmation&&confirmation!==p.submission.repo&&<p className="text-xs text-atlas-red">El nombre del repositorio no coincide.</p>}<div className="mt-4 flex justify-end gap-4"><button type="button" onClick={()=>dialog.current?.close()}>Cancelar</button><button disabled={confirmation!==p.submission.repo} className="rounded-lg bg-atlas-red p-3 text-sm text-white disabled:opacity-50">{admin?'Crear solicitud':'Eliminar e iniciar retención'}</button></div></form></dialog>
 </div>;
}
